flatpak install -y com.borgbase.Vorta
flatpak install -y com.brave.Browser
flatpak install -y com.github.PintaProject.Pinta
flatpak install -y com.github.tchx84.Flatseal
flatpak install -y com.rawtherapee.RawTherapee
flatpak install -y com.visualstudio.code
flatpak install -y io.github.shiftey.Desktop
flatpak install -y io.podman_desktop.PodmanDesktop
flatpak install -y net.giuspen.cherrytree
flatpak install -y org.darktable.Darktable
flatpak install -y org.freac.freac
flatpak install -y org.freefilesync.FreeFileSync
flatpak install -y org.geany.Geany
flatpak install -y org.gimp.GIMP
flatpak install -y org.keepassxc.KeePassXC
flatpak install -y org.libreoffice.LibreOffice
flatpak install -y org.raspberrypi.rpi-imager
flatpak install -y org.videolan.VLC
